#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

alias ll='ls -alhF'

# Map vim to nvim
alias vim="nvim"
alias vi="nvim"

#Custom Vars
export EDITOR=nvim
export HGEDITOR=nvim

# rbenv Installation
#export PATH="$HOME/.rbenv/bin:$PATH"
#eval "$(rbenv init -)"
PATH=$PATH:$HOME/bin
PATH=$PATH:$HOME/usr/bin

# Go Installation
export GOPATH=~/repos/go
export PATH="$PATH:/usr/local/go/bin"
export PATH="$PATH:$GOPATH/bin"

export TERM=screen-256color

alias resetaudio='sudo killall coreaudiod'

export PATH="$HOME/.cargo/bin:$PATH"


export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" --no-use  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

eval "$(atuin init zsh --disable-up-arrow)"

