#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

[ -f "/usr/facebook/ops/rc/master.zshrc" ] && source "/usr/facebook/ops/rc/master.zshrc"

# Customize to your needs...

alias ls='ls -F --color=auto'
alias ll='ls -alhF'
alias vim=nvim

# Map vim to nvim
alias vim="nvim"
alias vi="nvim"

# Print the nth column
function awkp() {
  awk "{print \$$1}"
}

# custom Vars
export EDITOR=nvim
export HGEDITOR=nvim

# rbenv Installation
#export PATH="$HOME/.rbenv/bin:$PATH"
#eval "$(rbenv init -)"
PATH=$PATH:$HOME/bin
PATH=$PATH:$HOME/usr/bin

# Go Installation
export GOPATH=~/repos/go
  export PATH="$PATH:/usr/local/go/bin"
export PATH="$PATH:$GOPATH/bin"

# uv
export PATH="/home/mbassem/.local/bin:$PATH"

# cargo
export PATH="$HOME/.cargo/bin:$PATH"
[ -f "$HOME/.cargo/env" ] && . "$HOME/.cargo/env"

# nvim
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" --no-use  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# atuin
[ -x "$(command -v atuin)" ] && eval "$(atuin init zsh --disable-up-arrow)"

# zoxide
[ -x "$(command -v zoxide)" ] && eval "$(zoxide init zsh)"

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# brew
[ -f /opt/homebrew/bin/brew ] && eval "$(/opt/homebrew/bin/brew shellenv)"
[ -f /home/linuxbrew/.linuxbrew/bin/brew ] && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

# direnv
[ -x "$(command -v direnv)" ] && eval "$(direnv hook zsh)"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# Android SDK
export ANDROID_HOME="$HOME/Library/Android/sdk"

# Volta
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"

# Pulumi
export PATH="$HOME/.pulumi/bin:$PATH"

# FZF with catppuccin theme
export FZF_DEFAULT_OPTS="--color=bg+:#414559,bg:#303446,spinner:#f2d5cf,hl:#e78284 --color=fg:#c6d0f5,header:#e78284,info:#ca9ee6,pointer:#f2d5cf --color=marker:#f2d5cf,fg+:#c6d0f5,prompt:#ca9ee6,hl+:#e78284"

export TERM=screen-256color

alias resetaudio='sudo killall coreaudiod'
alias xstream='xstream-rs'
alias claude="/home/mbassem/.claude/local/claude"
